### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by purerosefallen** [feisuzhu/thbattle#133]
i tried to use travis to compile, but always fails.
Are there any problems with the travis yml file#

**Comment by feisuzhu** [comment]
Hi, I didn't use the travis thing, that file could be introduced by one of the collaborators.

To compile, please run `pip install zc.buildout`  and `buildout`, which will install its dependencies and generate `bin/start_client` script for execution.

**Comment by purerosefallen** [comment]
So could you be so kind as to make a yml file of travis or appveyor to compile the game properly? Im a little lazy to make an account to dl from the forum. Thanks!

**Comment by feisuzhu** [comment]
Hi, sorry for late reply.

Travis building on `vnext` branch is now working, happy hacking.

Note that you can't play `vnext` branch on public server since `vnext` branch is newer than it, you must setup your own server (see `bin/start_server`) or keep source code synchronized with public server(which can be fetch from https://git.coding.net/proton/thbupdate-src.git)

**Comment by purerosefallen** [comment]
tried to fork and build by travis. it can successfully build, but how to launch the game?
